# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fa4509fea62d64d15debac7e9060ea16"
name = "locator-vs"
handle = "locator-vs"
application_url = "https://spider-encourage-ensures-institute.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "locations/create" ]
  uri = "/webhooks/locations/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_locations,write_locations"

[auth]
redirect_urls = [
  "https://spider-encourage-ensures-institute.trycloudflare.com/auth/callback",
  "https://spider-encourage-ensures-institute.trycloudflare.com/auth/shopify/callback",
  "https://spider-encourage-ensures-institute.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
